# Site settings
title: hacknight.it
email: riccardo@menodizero.it
description: "hacknight.it: a bunch of people hacking on free software."
baseurl: ""
url: "http://hacknight.it"
twitter_username: hacknightit
github_username: hacknightit

# Build settings
markdown: kramdown
permalink: pretty

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/hacknightit

# Postal address (add as many lines as necessary)
address:
  - line: Torino - IT

# Credits content
credits: ''
